apiVersion: apps/v1
kind: Deployment
metadata:
  name: reciter-pm-dev
  namespace: reciter
  labels:
    app: reciter-pm-dev
    environment: dev
    owner: szd2013
    tier: frontend
spec:
  selector:
    matchLabels:
      app: reciter-pm-dev
      tier: frontend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: reciter-pm-dev
        environment: dev
        tier: frontend
        owner: szd2013
    spec:
      containers:
      - image: reciter-publication-manager:dev_v2
        name: reciter-pm
        imagePullPolicy: IfNotPresent
        env:
          - name: NEXTAUTH_URL_INTERNAL
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: NEXTAUTH_URL_INTERNAL
          - name: NEXTAUTH_URL
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: NEXTAUTH_URL
          - name: RECITER_DB_NAME
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: RECITER_DB_NAME
          - name: RECITER_DB_USERNAME
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: RECITER_DB_USERNAME
          - name: RECITER_DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: RECITER_DB_PASSWORD
          - name: RECITER_DB_HOST
            valueFrom: 
              secretKeyRef:
                name: reciter-pm-dev-secrets
                key: RECITER_DB_HOST
          - name: LOGIN_PROVIDER
            value: SAML
        ports:
          - containerPort: 3000
            name: reciter-pm
        resources:
          requests:
            memory: 1500m
            cpu: '0.7'
          limits:
            memory: 2G
            cpu: '0.8'
        livenessProbe:
          httpGet:
            path: "/api/healthcheck"
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: "/api/healthcheck"
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
      nodeSelector:
          lifecycle: Ec2Spot
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reciter-pm-dev
  namespace: reciter
  labels:
    app: reciter-pm-dev
    environment: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reciter-pm-dev
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
