apiVersion: v1
kind: Secret
metadata:
  name:  reciter-pm-secrets
  namespace: reciter
  labels:
    app: reciter-pm
    environment: prod
    owner: szd2013
    tier: frontend
stringData:
  NEXTAUTH_URL_INTERNAL: <<NEXTAUTH_URL_INTERNAL>>
  NEXTAUTH_URL: <<NEXTAUTH_URL>>
  RECITER_DB_NAME: <<RECITER_DB_NAME>>
  RECITER_DB_USERNAME: <<RECITER_DB_USERNAME>> 
  RECITER_DB_PASSWORD: <<RECITER_DB_PASSWORD>>
  RECITER_DB_HOST: <<RECITER_DB_HOST>>
  RECITER_API_BASE_URL: <<RECITER_API_BASE_URL>>
  ENTITY_ID: <<ENTITY_ID>>
  ASSERT_ENDPOINT: <<ASSERT_ENDPOINT>>
  SSO_LOGIN_URL : <<SSO_LOGIN_URL>>
  SSO_LOGOUT_URL: <<SSO_LOGOUT_URL>>
  SMTP_HOST_NAME : <<SMTP_HOST_NAME>>
  NODE_ENV : <<NODE_ENV>>
  SMTP_USER: <<SMTP_USER>>
  SMTP_PASSWORD: <<SMTP_PASSWORD>>
  SMTP_ADMIN_EMAIL : <<SMTP_ADMIN_EMAIL>>
  ASMS_API_BASE_URL : <<ASMS_API_BASE_URL>>
  ASMS_USER_TRACKING_API_AUTHORIZATON : <<ASMS_USER_TRACKING_API_AUTHORIZATON>>
type: Opaque
